export const CATEGORIES = [
  { id: 1, name: 'Script', group: 'Core source code' },
  { id: 2, name: 'Code snippet', group: 'Core source code' },
  { id: 3, name: 'Function', group: 'Core source code' },
  { id: 4, name: 'Class', group: 'Core source code' },
  { id: 5, name: 'Module', group: 'Core source code' },
  { id: 6, name: 'Library/package code', group: 'Core source code' },
  { id: 7, name: 'Algorithm implementation', group: 'Core source code' },
  { id: 8, name: 'Data structure implementation', group: 'Core source code' },
  { id: 9, name: 'Utility/helper code', group: 'Core source code' },
  { id: 10, name: 'CLI command/tool', group: 'Core source code' },
  { id: 11, name: 'Application entry point', group: 'Core source code' },
  { id: 12, name: 'Error handling block', group: 'Core source code' },
  { id: 13, name: 'Logging/telemetry code', group: 'Core source code' },
  { id: 14, name: 'Async/concurrency code', group: 'Core source code' },
  { id: 15, name: 'File I/O code', group: 'Core source code' },
  { id: 16, name: 'Network/socket code', group: 'Core source code' },
  { id: 17, name: 'API client code', group: 'Core source code' },

  { id: 18, name: 'Backend route/endpoint', group: 'Backend/API' },
  { id: 19, name: 'Controller', group: 'Backend/API' },
  { id: 20, name: 'Service/business logic', group: 'Backend/API' },
  { id: 21, name: 'Middleware', group: 'Backend/API' },
  { id: 22, name: 'Model/entity', group: 'Backend/API' },
  { id: 23, name: 'Serializer/DTO/schema object', group: 'Backend/API' },
  { id: 24, name: 'Validation logic', group: 'Backend/API' },
  { id: 25, name: 'Authentication code', group: 'Backend/API' },
  { id: 26, name: 'Authorization code', group: 'Backend/API' },

  { id: 27, name: 'UI component', group: 'Frontend/UI' },
  { id: 28, name: 'Page/screen component', group: 'Frontend/UI' },
  { id: 29, name: 'Layout/template', group: 'Frontend/UI' },
  { id: 30, name: 'Form component', group: 'Frontend/UI' },
  { id: 31, name: 'State management code', group: 'Frontend/UI' },
  { id: 32, name: 'Hook/composable', group: 'Frontend/UI' },
  { id: 33, name: 'Styling code', group: 'Frontend/UI' },
  { id: 34, name: 'Animation/interaction code', group: 'Frontend/UI' },
  { id: 35, name: 'Design-system component', group: 'Frontend/UI' },

  { id: 36, name: 'Database schema', group: 'Database/data layer' },
  { id: 37, name: 'Database migration', group: 'Database/data layer' },
  { id: 38, name: 'SQL query', group: 'Database/data layer' },
  { id: 39, name: 'Stored procedure/function', group: 'Database/data layer' },
  { id: 40, name: 'Database trigger', group: 'Database/data layer' },
  { id: 41, name: 'Seed data', group: 'Database/data layer' },
  { id: 42, name: 'ORM model', group: 'Database/data layer' },
  { id: 43, name: 'Data access/repository', group: 'Database/data layer' },
  { id: 44, name: 'Data transformation', group: 'Database/data layer' },

  { id: 45, name: 'Configuration file', group: 'Development environment/tooling' },
  { id: 46, name: 'Environment setup', group: 'Development environment/tooling' },
  { id: 47, name: 'Dependency manifest', group: 'Development environment/tooling' },
  { id: 48, name: 'Build script', group: 'Development environment/tooling' },
  { id: 49, name: 'Bundler config', group: 'Development environment/tooling' },
  { id: 50, name: 'Compiler/transpiler config', group: 'Development environment/tooling' },
  { id: 51, name: 'Linter config', group: 'Development environment/tooling' },
  { id: 52, name: 'Formatter config', group: 'Development environment/tooling' },
  { id: 53, name: 'Git hook', group: 'Development environment/tooling' },
  { id: 54, name: 'IDE/editor config', group: 'Development environment/tooling' },

  { id: 55, name: 'Dockerfile', group: 'Deployment/infrastructure/operations' },
  { id: 56, name: 'Docker Compose file', group: 'Deployment/infrastructure/operations' },
  { id: 57, name: 'Kubernetes manifest', group: 'Deployment/infrastructure/operations' },
  { id: 58, name: 'Infrastructure as Code', group: 'Deployment/infrastructure/operations' },
  { id: 59, name: 'CI/CD pipeline', group: 'Deployment/infrastructure/operations' },
  { id: 60, name: 'Deployment script', group: 'Deployment/infrastructure/operations' },
  { id: 61, name: 'Monitoring/alert config', group: 'Deployment/infrastructure/operations' },

  { id: 62, name: 'Unit test', group: 'Testing/security/quality' },
  { id: 63, name: 'Integration test', group: 'Testing/security/quality' },
  { id: 64, name: 'End-to-end test', group: 'Testing/security/quality' },
  { id: 65, name: 'Mock/stub/fake', group: 'Testing/security/quality' },
  { id: 66, name: 'Benchmark/performance test', group: 'Testing/security/quality' },
  { id: 67, name: 'Security test/config', group: 'Testing/security/quality' },

  { id: 68, name: 'Notebook cell', group: 'Data science/docs/examples' },
  { id: 69, name: 'Data analysis code', group: 'Data science/docs/examples' },
  { id: 70, name: 'Machine learning code', group: 'Data science/docs/examples' },
  { id: 71, name: 'Documentation example', group: 'Data science/docs/examples' },
  { id: 72, name: 'Pseudocode', group: 'Data science/docs/examples' },

  { id: 73, name: 'Canvas mockup/schema', group: 'Design/Architecture' }
];

export const CATEGORY_GROUPS = [
  'Core source code',
  'Backend/API',
  'Frontend/UI',
  'Database/data layer',
  'Development environment/tooling',
  'Deployment/infrastructure/operations',
  'Testing/security/quality',
  'Data science/docs/examples',
  'Design/Architecture'
];

export const FILE_TYPES = [
  // Source code files
  { ext: '.py', group: 'Source code files', label: 'Python (.py)' },
  { ext: '.pyi', group: 'Source code files', label: 'Python Interface (.pyi)' },
  { ext: '.pyw', group: 'Source code files', label: 'Python Windowed (.pyw)' },
  { ext: '.ipynb', group: 'Source code files', label: 'Jupyter Notebook (.ipynb)' },
  { ext: '.c', group: 'Source code files', label: 'C (.c)' },
  { ext: '.h', group: 'Source code files', label: 'C Header (.h)' },
  { ext: '.cpp', group: 'Source code files', label: 'C++ (.cpp)' },
  { ext: '.cc', group: 'Source code files', label: 'C++ (.cc)' },
  { ext: '.cxx', group: 'Source code files', label: 'C++ (.cxx)' },
  { ext: '.hpp', group: 'Source code files', label: 'C++ Header (.hpp)' },
  { ext: '.hh', group: 'Source code files', label: 'C++ Header (.hh)' },
  { ext: '.hxx', group: 'Source code files', label: 'C++ Header (.hxx)' },
  { ext: '.ipp', group: 'Source code files', label: 'C++ Inline (.ipp)' },
  { ext: '.ixx', group: 'Source code files', label: 'C++ Module (.ixx)' },
  { ext: '.m', group: 'Source code files', label: 'Objective-C (.m)' },
  { ext: '.mm', group: 'Source code files', label: 'Objective-C++ (.mm)' },
  { ext: '.java', group: 'Source code files', label: 'Java (.java)' },
  { ext: '.kt', group: 'Source code files', label: 'Kotlin (.kt)' },
  { ext: '.kts', group: 'Source code files', label: 'Kotlin Script (.kts)' },
  { ext: '.scala', group: 'Source code files', label: 'Scala (.scala)' },
  { ext: '.sc', group: 'Source code files', label: 'Scala Script (.sc)' },
  { ext: '.groovy', group: 'Source code files', label: 'Groovy (.groovy)' },
  { ext: '.js', group: 'Source code files', label: 'JavaScript (.js)' },
  { ext: '.mjs', group: 'Source code files', label: 'JavaScript Module (.mjs)' },
  { ext: '.cjs', group: 'Source code files', label: 'CommonJS (.cjs)' },
  { ext: '.jsx', group: 'Source code files', label: 'React JSX (.jsx)' },
  { ext: '.ts', group: 'Source code files', label: 'TypeScript (.ts)' },
  { ext: '.tsx', group: 'Source code files', label: 'React TSX (.tsx)' },
  { ext: '.dart', group: 'Source code files', label: 'Dart (.dart)' },
  { ext: '.go', group: 'Source code files', label: 'Go (.go)' },
  { ext: '.rs', group: 'Source code files', label: 'Rust (.rs)' },
  { ext: '.rb', group: 'Source code files', label: 'Ruby (.rb)' },
  { ext: '.php', group: 'Source code files', label: 'PHP (.php)' },
  { ext: '.swift', group: 'Source code files', label: 'Swift (.swift)' },
  { ext: '.cs', group: 'Source code files', label: 'C# (.cs)' },
  { ext: '.fs', group: 'Source code files', label: 'F# (.fs)' },
  { ext: '.fsx', group: 'Source code files', label: 'F# Script (.fsx)' },
  { ext: '.vb', group: 'Source code files', label: 'Visual Basic (.vb)' },
  { ext: '.sh', group: 'Source code files', label: 'Shell (.sh)' },
  { ext: '.bash', group: 'Source code files', label: 'Bash (.bash)' },
  { ext: '.zsh', group: 'Source code files', label: 'Zsh (.zsh)' },
  { ext: '.fish', group: 'Source code files', label: 'Fish (.fish)' },
  { ext: '.ps1', group: 'Source code files', label: 'PowerShell (.ps1)' },
  { ext: '.psm1', group: 'Source code files', label: 'PowerShell Module (.psm1)' },
  { ext: '.psd1', group: 'Source code files', label: 'PowerShell Data (.psd1)' },
  { ext: '.bat', group: 'Source code files', label: 'Batch (.bat)' },
  { ext: '.cmd', group: 'Source code files', label: 'Command (.cmd)' },
  { ext: '.pl', group: 'Source code files', label: 'Perl (.pl)' },
  { ext: '.pm', group: 'Source code files', label: 'Perl Module (.pm)' },
  { ext: '.lua', group: 'Source code files', label: 'Lua (.lua)' },
  { ext: '.r', group: 'Source code files', label: 'R (.r)' },
  { ext: '.jl', group: 'Source code files', label: 'Julia (.jl)' },
  { ext: '.hs', group: 'Source code files', label: 'Haskell (.hs)' },
  { ext: '.lhs', group: 'Source code files', label: 'Literate Haskell (.lhs)' },
  { ext: '.erl', group: 'Source code files', label: 'Erlang (.erl)' },
  { ext: '.hrl', group: 'Source code files', label: 'Erlang Header (.hrl)' },
  { ext: '.ex', group: 'Source code files', label: 'Elixir (.ex)' },
  { ext: '.exs', group: 'Source code files', label: 'Elixir Script (.exs)' },
  { ext: '.clj', group: 'Source code files', label: 'Clojure (.clj)' },
  { ext: '.cljs', group: 'Source code files', label: 'ClojureScript (.cljs)' },
  { ext: '.lisp', group: 'Source code files', label: 'Lisp (.lisp)' },
  { ext: '.lsp', group: 'Source code files', label: 'Lisp (.lsp)' },
  { ext: '.scm', group: 'Source code files', label: 'Scheme (.scm)' },
  { ext: '.rkt', group: 'Source code files', label: 'Racket (.rkt)' },
  { ext: '.ml', group: 'Source code files', label: 'OCaml (.ml)' },
  { ext: '.mli', group: 'Source code files', label: 'OCaml Interface (.mli)' },
  { ext: '.re', group: 'Source code files', label: 'Reason (.re)' },
  { ext: '.res', group: 'Source code files', label: 'ReScript (.res)' },
  { ext: '.forth', group: 'Source code files', label: 'Forth (.forth)' },
  { ext: '.f90', group: 'Source code files', label: 'Fortran 90 (.f90)' },
  { ext: '.f95', group: 'Source code files', label: 'Fortran 95 (.f95)' },
  { ext: '.f', group: 'Source code files', label: 'Fortran (.f)' },
  { ext: '.cob', group: 'Source code files', label: 'COBOL (.cob)' },
  { ext: '.adb', group: 'Source code files', label: 'Ada Body (.adb)' },
  { ext: '.ads', group: 'Source code files', label: 'Ada Spec (.ads)' },
  { ext: '.d', group: 'Source code files', label: 'D (.d)' },
  { ext: '.nim', group: 'Source code files', label: 'Nim (.nim)' },
  { ext: '.cr', group: 'Source code files', label: 'Crystal (.cr)' },
  { ext: '.zig', group: 'Source code files', label: 'Zig (.zig)' },
  { ext: '.v', group: 'Source code files', label: 'V (.v)' },
  { ext: '.odin', group: 'Source code files', label: 'Odin (.odin)' },
  { ext: '.pas', group: 'Source code files', label: 'Pascal (.pas)' },
  { ext: '.dpr', group: 'Source code files', label: 'Delphi Project (.dpr)' },
  { ext: '.asm', group: 'Source code files', label: 'Assembly (.asm)' },
  { ext: '.s', group: 'Source code files', label: 'Assembly (.s)' },
  { ext: '.nasm', group: 'Source code files', label: 'NASM (.nasm)' },
  { ext: '.ll', group: 'Source code files', label: 'LLVM IR (.ll)' },
  { ext: '.wat', group: 'Source code files', label: 'WebAssembly Text (.wat)' },
  { ext: '.sol', group: 'Source code files', label: 'Solidity (.sol)' },
  { ext: '.vy', group: 'Source code files', label: 'Vyper (.vy)' },
  { ext: '.move', group: 'Source code files', label: 'Move (.move)' },
  { ext: '.cls', group: 'Source code files', label: 'Apex (.cls)' },
  { ext: '.abap', group: 'Source code files', label: 'ABAP (.abap)' },
  { ext: '.tcl', group: 'Source code files', label: 'Tcl (.tcl)' },
  { ext: '.ahk', group: 'Source code files', label: 'AutoHotkey (.ahk)' },
  { ext: '.au3', group: 'Source code files', label: 'AutoIt (.au3)' },
  { ext: '.applescript', group: 'Source code files', label: 'AppleScript (.applescript)' },
  { ext: '.coffee', group: 'Source code files', label: 'CoffeeScript (.coffee)' },
  { ext: '.elm', group: 'Source code files', label: 'Elm (.elm)' },
  { ext: '.purs', group: 'Source code files', label: 'PureScript (.purs)' },
  { ext: '.idr', group: 'Source code files', label: 'Idris (.idr)' },
  { ext: '.agda', group: 'Source code files', label: 'Agda (.agda)' },
  { ext: '.lean', group: 'Source code files', label: 'Lean (.lean)' },
  { ext: '.st', group: 'Source code files', label: 'Smalltalk (.st)' },
  { ext: '.pde', group: 'Source code files', label: 'Processing (.pde)' },
  { ext: '.ino', group: 'Source code files', label: 'Arduino (.ino)' },

  // Web and UI files
  { ext: '.html', group: 'Web and UI files', label: 'HTML (.html)' },
  { ext: '.htm', group: 'Web and UI files', label: 'HTML (.htm)' },
  { ext: '.xhtml', group: 'Web and UI files', label: 'XHTML (.xhtml)' },
  { ext: '.css', group: 'Web and UI files', label: 'CSS (.css)' },
  { ext: '.scss', group: 'Web and UI files', label: 'Sass (.scss)' },
  { ext: '.sass', group: 'Web and UI files', label: 'Sass (.sass)' },
  { ext: '.less', group: 'Web and UI files', label: 'Less (.less)' },
  { ext: '.pcss', group: 'Web and UI files', label: 'PostCSS (.pcss)' },
  { ext: '.vue', group: 'Web and UI files', label: 'Vue (.vue)' },
  { ext: '.svelte', group: 'Web and UI files', label: 'Svelte (.svelte)' },
  { ext: '.astro', group: 'Web and UI files', label: 'Astro (.astro)' },
  { ext: '.qml', group: 'Web and UI files', label: 'QML (.qml)' },
  { ext: '.cshtml', group: 'Web and UI files', label: 'C# HTML (.cshtml)' },
  { ext: '.vbhtml', group: 'Web and UI files', label: 'VB HTML (.vbhtml)' },
  { ext: '.aspx', group: 'Web and UI files', label: 'ASP.NET Page (.aspx)' },
  { ext: '.ashx', group: 'Web and UI files', label: 'ASP.NET Handler (.ashx)' },
  { ext: '.asax', group: 'Web and UI files', label: 'ASP.NET App (.asax)' },
  { ext: '.jsp', group: 'Web and UI files', label: 'JSP (.jsp)' },
  { ext: '.jspf', group: 'Web and UI files', label: 'JSP Fragment (.jspf)' },

  // Markup and documentation files
  { ext: '.md', group: 'Markup and documentation files', label: 'Markdown (.md)' },
  { ext: '.mdx', group: 'Markup and documentation files', label: 'MDX (.mdx)' },
  { ext: '.rst', group: 'Markup and documentation files', label: 'reStructuredText (.rst)' },
  { ext: '.adoc', group: 'Markup and documentation files', label: 'AsciiDoc (.adoc)' },
  { ext: '.txt', group: 'Markup and documentation files', label: 'Text (.txt)' },
  { ext: '.tex', group: 'Markup and documentation files', label: 'TeX (.tex)' },
  { ext: '.bib', group: 'Markup and documentation files', label: 'BibTeX (.bib)' },
  { ext: '.biblatex', group: 'Markup and documentation files', label: 'BibLaTeX (.biblatex)' },
  { ext: '.xml', group: 'Markup and documentation files', label: 'XML (.xml)' },
  { ext: '.xsd', group: 'Markup and documentation files', label: 'XML Schema (.xsd)' },
  { ext: '.xsl', group: 'Markup and documentation files', label: 'XSL (.xsl)' },
  { ext: '.xslt', group: 'Markup and documentation files', label: 'XSLT (.xslt)' },
  { ext: '.dtd', group: 'Markup and documentation files', label: 'DTD (.dtd)' },
  { ext: '.svg', group: 'Markup and documentation files', label: 'SVG (.svg)' },
  { ext: '.man', group: 'Markup and documentation files', label: 'Man Page (.man)' },

  // Data and config files
  { ext: '.json', group: 'Data and config files', label: 'JSON (.json)' },
  { ext: '.jsonc', group: 'Data and config files', label: 'JSON with Comments (.jsonc)' },
  { ext: '.json5', group: 'Data and config files', label: 'JSON5 (.json5)' },
  { ext: '.yaml', group: 'Data and config files', label: 'YAML (.yaml)' },
  { ext: '.yml', group: 'Data and config files', label: 'YAML (.yml)' },
  { ext: '.toml', group: 'Data and config files', label: 'TOML (.toml)' },
  { ext: '.ini', group: 'Data and config files', label: 'INI (.ini)' },
  { ext: '.env', group: 'Data and config files', label: 'Dotenv (.env)' },
  { ext: '.conf', group: 'Data and config files', label: 'Config (.conf)' },
  { ext: '.properties', group: 'Data and config files', label: 'Properties (.properties)' },
  { ext: '.csv', group: 'Data and config files', label: 'CSV (.csv)' },
  { ext: '.tsv', group: 'Data and config files', label: 'TSV (.tsv)' },
  { ext: '.graphql', group: 'Data and config files', label: 'GraphQL (.graphql)' },
  { ext: '.gql', group: 'Data and config files', label: 'GraphQL (.gql)' },
  { ext: '.proto', group: 'Data and config files', label: 'Protocol Buffers (.proto)' },
  { ext: '.fbs', group: 'Data and config files', label: 'FlatBuffers (.fbs)' },
  { ext: '.thrift', group: 'Data and config files', label: 'Thrift (.thrift)' },
  { ext: '.capnp', group: 'Data and config files', label: 'Cap\'n Proto (.capnp)' },
  { ext: '.raml', group: 'Data and config files', label: 'RAML (.raml)' },
  { ext: '.wsdl', group: 'Data and config files', label: 'WSDL (.wsdl)' },
  { ext: '.webmanifest', group: 'Data and config files', label: 'Web Manifest (.webmanifest)' },
  { ext: '.map', group: 'Data and config files', label: 'Source Map (.map)' },
  { ext: '.lock', group: 'Data and config files', label: 'Lockfile (.lock)' },
  { ext: '.editorconfig', group: 'Data and config files', label: 'EditorConfig (.editorconfig)' },

  // SQL and database text files
  { ext: '.sql', group: 'SQL and database text files', label: 'SQL (.sql)' },
  { ext: '.pls', group: 'SQL and database text files', label: 'PL/SQL (.pls)' },
  { ext: '.psql', group: 'SQL and database text files', label: 'PostgreSQL (.psql)' },
  { ext: '.mysql', group: 'SQL and database text files', label: 'MySQL (.mysql)' },

  // Template files
  { ext: '.hbs', group: 'Template files', label: 'Handlebars (.hbs)' },
  { ext: '.mustache', group: 'Template files', label: 'Mustache (.mustache)' },
  { ext: '.twig', group: 'Template files', label: 'Twig (.twig)' },
  { ext: '.jinja', group: 'Template files', label: 'Jinja (.jinja)' },
  { ext: '.j2', group: 'Template files', label: 'Jinja2 (.j2)' },
  { ext: '.liquid', group: 'Template files', label: 'Liquid (.liquid)' },
  { ext: '.pug', group: 'Template files', label: 'Pug (.pug)' },
  { ext: '.haml', group: 'Template files', label: 'Haml (.haml)' },
  { ext: '.slim', group: 'Template files', label: 'Slim (.slim)' },
  { ext: '.ejs', group: 'Template files', label: 'EJS (.ejs)' },
  { ext: '.njk', group: 'Template files', label: 'Nunjucks (.njk)' },
  { ext: '.ftl', group: 'Template files', label: 'FreeMarker (.ftl)' },
  { ext: '.vm', group: 'Template files', label: 'Velocity (.vm)' },
  { ext: '.tpl', group: 'Template files', label: 'Template (.tpl)' },
  { ext: '.erb', group: 'Template files', label: 'ERB (.erb)' },

  // Build and project files
  { ext: '.cmake', group: 'Build and project files', label: 'CMake (.cmake)' },
  { ext: '.ninja', group: 'Build and project files', label: 'Ninja (.ninja)' },
  { ext: '.bazel', group: 'Build and project files', label: 'Bazel (.bazel)' },
  { ext: '.gradle', group: 'Build and project files', label: 'Gradle (.gradle)' },
  { ext: '.sbt', group: 'Build and project files', label: 'SBT (.sbt)' },
  { ext: '.nuspec', group: 'Build and project files', label: 'NuGet Spec (.nuspec)' },
  { ext: '.csproj', group: 'Build and project files', label: 'C# Project (.csproj)' },
  { ext: '.vbproj', group: 'Build and project files', label: 'VB Project (.vbproj)' },
  { ext: '.fsproj', group: 'Build and project files', label: 'F# Project (.fsproj)' },
  { ext: '.sln', group: 'Build and project files', label: 'Visual Studio Solution (.sln)' },
  { ext: '.pbxproj', group: 'Build and project files', label: 'Xcode Project (.pbxproj)' },

  // DevOps and infrastructure files
  { ext: '.tf', group: 'DevOps and infrastructure files', label: 'Terraform (.tf)' },
  { ext: '.tfvars', group: 'DevOps and infrastructure files', label: 'Terraform Vars (.tfvars)' },
  { ext: '.tofu', group: 'DevOps and infrastructure files', label: 'OpenTofu (.tofu)' },
  { ext: '.hcl', group: 'DevOps and infrastructure files', label: 'HCL (.hcl)' },
  { ext: '.nomad', group: 'DevOps and infrastructure files', label: 'Nomad (.nomad)' },
  { ext: '.template', group: 'DevOps and infrastructure files', label: 'CloudFormation (.template)' },

  // Version control and tool config files
  { ext: '.gitignore', group: 'Version control and tool config files', label: 'Git Ignore (.gitignore)' },
  { ext: '.gitattributes', group: 'Version control and tool config files', label: 'Git Attributes (.gitattributes)' },
  { ext: '.gitmodules', group: 'Version control and tool config files', label: 'Git Modules (.gitmodules)' },
  { ext: '.gitconfig', group: 'Version control and tool config files', label: 'Git Config (.gitconfig)' },
  { ext: '.npmignore', group: 'Version control and tool config files', label: 'NPM Ignore (.npmignore)' },
  { ext: '.dockerignore', group: 'Version control and tool config files', label: 'Docker Ignore (.dockerignore)' },
  { ext: '.hgignore', group: 'Version control and tool config files', label: 'Mercurial Ignore (.hgignore)' },
  { ext: '.eslintrc', group: 'Version control and tool config files', label: 'ESLint Config (.eslintrc)' },
  { ext: '.prettierrc', group: 'Version control and tool config files', label: 'Prettier Config (.prettierrc)' },
  { ext: '.babelrc', group: 'Version control and tool config files', label: 'Babel Config (.babelrc)' },
  { ext: '.browserslistrc', group: 'Version control and tool config files', label: 'Browserslist (.browserslistrc)' },
  { ext: '.stylelintrc', group: 'Version control and tool config files', label: 'Stylelint Config (.stylelintrc)' },
  { ext: '.jshintrc', group: 'Version control and tool config files', label: 'JSHint Config (.jshintrc)' },
  { ext: '.jestrc', group: 'Version control and tool config files', label: 'Jest Config (.jestrc)' },
  { ext: '.mocharc', group: 'Version control and tool config files', label: 'Mocha Config (.mocharc)' },
  { ext: '.commitlintrc', group: 'Version control and tool config files', label: 'Commitlint Config (.commitlintrc)' },
  { ext: '.code-workspace', group: 'Version control and tool config files', label: 'VS Code Workspace (.code-workspace)' },
  { ext: '.iml', group: 'Version control and tool config files', label: 'IntelliJ Module (.iml)' },
  { ext: '.ignore', group: 'Version control and tool config files', label: 'Ignore File (.ignore)' },

  // Testing, logs, and reports
  { ext: '.log', group: 'Testing, logs, and reports', label: 'Log File (.log)' },
  { ext: '.trace', group: 'Testing, logs, and reports', label: 'Trace File (.trace)' },
  { ext: '.lcov', group: 'Testing, logs, and reports', label: 'LCOV Report (.lcov)' },
  { ext: '.coverage', group: 'Testing, logs, and reports', label: 'Coverage Report (.coverage)' },
  { ext: '.snap', group: 'Testing, logs, and reports', label: 'Jest Snapshot (.snap)' },
  { ext: '.har', group: 'Testing, logs, and reports', label: 'HTTP Archive (.har)' },

  // Security text files
  { ext: '.pem', group: 'Security text files', label: 'PEM Certificate (.pem)' },
  { ext: '.crt', group: 'Security text files', label: 'Certificate (.crt)' },
  { ext: '.cer', group: 'Security text files', label: 'Certificate (.cer)' },
  { ext: '.csr', group: 'Security text files', label: 'Certificate Signing Request (.csr)' },
  { ext: '.pub', group: 'Security text files', label: 'Public Key (.pub)' },
  { ext: '.key', group: 'Security text files', label: 'Private Key (.key)' },
  { ext: '.asc', group: 'Security text files', label: 'PGP ASCII Armor (.asc)' },

  // Game development text files
  { ext: '.tscn', group: 'Game development text files', label: 'Godot Scene (.tscn)' },
  { ext: '.tres', group: 'Game development text files', label: 'Godot Resource (.tres)' },
  { ext: '.rpy', group: 'Game development text files', label: 'Ren\'Py Script (.rpy)' },

  // Extensionless IDE-editable special files
  { ext: 'Makefile', group: 'Extensionless IDE-editable special files', label: 'Makefile' },
  { ext: 'Dockerfile', group: 'Extensionless IDE-editable special files', label: 'Dockerfile' },
  { ext: 'Jenkinsfile', group: 'Extensionless IDE-editable special files', label: 'Jenkinsfile' },
  { ext: 'Vagrantfile', group: 'Extensionless IDE-editable special files', label: 'Vagrantfile' },
  { ext: 'Gemfile', group: 'Extensionless IDE-editable special files', label: 'Gemfile' },
  { ext: 'Pipfile', group: 'Extensionless IDE-editable special files', label: 'Pipfile' },
  { ext: 'README', group: 'Extensionless IDE-editable special files', label: 'README' },
  { ext: 'LICENSE', group: 'Extensionless IDE-editable special files', label: 'LICENSE' },
  { ext: 'CHANGELOG', group: 'Extensionless IDE-editable special files', label: 'CHANGELOG' },
  { ext: 'AUTHORS', group: 'Extensionless IDE-editable special files', label: 'AUTHORS' },
  { ext: 'CONTRIBUTORS', group: 'Extensionless IDE-editable special files', label: 'CONTRIBUTORS' },
  { ext: 'NOTICE', group: 'Extensionless IDE-editable special files', label: 'NOTICE' },
  { ext: 'CODEOWNERS', group: 'Extensionless IDE-editable special files', label: 'CODEOWNERS' },
  { ext: 'WORKSPACE', group: 'Extensionless IDE-editable special files', label: 'WORKSPACE' },
  { ext: 'BUCK', group: 'Extensionless IDE-editable special files', label: 'BUCK' },

  // Design and mockup files
  { ext: 'excalidraw', group: 'Design and mockup files', label: 'Excalidraw (.excalidraw)' }
];

export const FILE_TYPE_GROUPS = [
  'Source code files',
  'Web and UI files',
  'Markup and documentation files',
  'Data and config files',
  'SQL and database text files',
  'Template files',
  'Build and project files',
  'DevOps and infrastructure files',
  'Version control and tool config files',
  'Testing, logs, and reports',
  'Security text files',
  'Game development text files',
  'Extensionless IDE-editable special files',
  'Design and mockup files'
];

function stringToColor(str) {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = str.charCodeAt(i) + ((hash << 5) - hash);
  }
  const hue = Math.abs(hash) % 360;
  return `hsl(${hue}, 75%, 15%)`;
}

export function getFileColor(ext) {
  if (!ext) return 'var(--accent-secondary)';
  return stringToColor(ext);
}

export function getCategoryColor(categoryName) {
  if (!categoryName) return 'var(--accent-secondary)';
  return stringToColor(categoryName);
}
